title: Kelton Santos  # your name (or website title) here

logo: "/images/logo.png?raw=true" # your photo (or logo) here


 description: # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/kelton-garcia-santos-a75060b3/">LinkedIn</a> |
  <a href="https://github.com/keltonsantos">GitHub</a>
  </p> 

    <p align="justify">
  I am passionate about Data Analysis & Visualization. 
 
  <br><br>
   As part of my career goals to improve my data skills, I've built this portfolio website to keep track of my learning.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
