title: > # the title goes here
  <p align="center"> 
  Kelton Santos 
  </p>  

logo: "/images/logo.png?size=20%" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/kelton-garcia-santos-a75060b3/">LinkedIn</a> |
  <a href="https://github.com/keltonsantos">GitHub</a>
  </p> 

  <p align="justify">
  I am passionate about Data Analysis & Visualization. 
 
  <br><br>
   As part of my career goals to improve my data skills, I've built this portfolio website to keep track of my learning.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: G-VX2CYT6CJ6 # your Google Analytics tracking ID here
